version: '3'
services:
  bestgems-app:
    image: bestgems-app
    build:
      context: ../
      dockerfile: docker/bestgems-app/Dockerfile
    ports:
      - 9292:9292
    environment:
      - RACK_ENV=production
      - APP_ENV=production
      - BESTGEMS_DB_HOST=bestgems-db
      - BESTGEMS_DB_USER=bestgems
      - BESTGEMS_DB_PASSWORD=bestgems
      - BESTGEMS_DB_NAME=bestgems
      - BESTGEMS_LEVELDB_DIR=db/trends
    command: /bin/bash -c 'wait-for-it.sh bestgems-db:5432 && bundle exec rake db:migration && bin/start'
  bestgems-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=bestgems
      - POSTGRES_PASSWORD=bestgems
